name: react-native-android-build
on:
  push:
    branches:
      - main
jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install
  generate-apk:
    needs: setup-node
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install
      - name: Build Debug APK
        run: npm run android:debug
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/